flowchart LR
  n_0z9E0N_xJpJcTOEVbup4_10["node_up4-10"]
  n_0z9E0N_xJpJcTOEVbup4_11["control_unit"]
  n_0z9E0N_xJpJcTOEVbup4_12["sw[2:0]"]
  n_0z9E0N_xJpJcTOEVbup4_13["run_en"]
  n_0z9E0N_xJpJcTOEVbup4_14["clear_en"]
  n_0z9E0N_xJpJcTOEVbup4_15["down_mode"]
  n_0z9E0N_xJpJcTOEVbup4_20["node_up4-20"]
  n_0z9E0N_xJpJcTOEVbup4_21["datapath"]
  n_0z9E0N_xJpJcTOEVbup4_22["node_up4-22"]
  n_0z9E0N_xJpJcTOEVbup4_23["tick_gen"]
  n_0z9E0N_xJpJcTOEVbup4_24["clk"]
  n_0z9E0N_xJpJcTOEVbup4_25["rst"]
  n_0z9E0N_xJpJcTOEVbup4_26["run_en"]
  n_0z9E0N_xJpJcTOEVbup4_27["tick"]
  n_0z9E0N_xJpJcTOEVbup4_3["clk"]
  n_0z9E0N_xJpJcTOEVbup4_32["node_up4-32"]
  n_0z9E0N_xJpJcTOEVbup4_33["tick_counter"]
  n_0z9E0N_xJpJcTOEVbup4_34["clk"]
  n_0z9E0N_xJpJcTOEVbup4_35["rst"]
  n_0z9E0N_xJpJcTOEVbup4_36["tick"]
  n_0z9E0N_xJpJcTOEVbup4_37["run_en"]
  n_0z9E0N_xJpJcTOEVbup4_38["clear_en"]
  n_0z9E0N_xJpJcTOEVbup4_39["down_mode"]
  n_0z9E0N_xJpJcTOEVbup4_49["count_out[13:0]"]
  n_0z9E0N_xJpJcTOEVbup4_5["rst"]
  n_0z9E0N_xJpJcTOEVbup4_7["sw[2:0]"]
  n_0z9E0N_xJpJcTOEVbup4_22 --> n_0z9E0N_xJpJcTOEVbup4_32
  n_0z9E0N_xJpJcTOEVbup4_3 --> n_0z9E0N_xJpJcTOEVbup4_24
  n_0z9E0N_xJpJcTOEVbup4_5 --> n_0z9E0N_xJpJcTOEVbup4_25
  n_0z9E0N_xJpJcTOEVbup4_10 --> n_0z9E0N_xJpJcTOEVbup4_32
  n_0z9E0N_xJpJcTOEVbup4_7 --> n_0z9E0N_xJpJcTOEVbup4_12
  n_0z9E0N_xJpJcTOEVbup4_32 --> n_0z9E0N_xJpJcTOEVbup4_49
